server:
  port: ${SERVER.PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/v3/api-docs

app:
  jwt:
    secret: ${JWT_SECRET}
    accessLifetimeMs: ${JWT_ACCESS_LIFETIME}
    refreshLifetimeMs: ${JWT_REFRESH_LIFETIME}
    issuer: ${JWT_ISSUER}

s3:
  url: ${S3_URL}
  bucket: ${S3_BUCKET}

fontPath: "arial.ttf"

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  senderAddress: ${SENDER_ADDRESS}
  senderPassword: ${SENDER_PASSWORD}

