server:
  port: ${SERVER.PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/v3/api-docs

app:
  jwt:
    secret: ${JWT_SECRET}
    lifetimeMs: ${JWT_LIFETIME}
    issuer: ${JWT_ISSUER}

