env:
  - name: DATABASE_URL
    value: "jdbc:postgresql://192.168.88.141:5432/learnit_db"
  - name: DATABASE_USERNAME
    value: "Learnit"
  - name: DATABASE_PASSWORD
    value: "HiMFt3wPo4"
  - name: JWT_ACCESS_LIFETIME
    value: "86400000"
  - name: JWT_REFRESH_LIFETIME
    value: "2596000000"
  - name: JWT_SECRET
    value: "qwasdqwefa"
  - name: JWT_ISSUER
    value: "irlix"
  - name: S3_BUCKET
    value: "learnit-prod"
  - name: S3_URL
    value: "http://192.168.88.42:30302"
  - name: MAIL_HOST
    value: "smtp.mail.ru"
  - name: MAIL_PORT
    value: "587"
  - name: SENDER_ADDRESS
    value: "learnit_recovery@mail.ru"
  - name: SENDER_PASSWORD
    value: "i9CKFRr9m0EG38v8QHGo"

ingress:
  enabled: true
  className: ""
  annotations:
    # IMPORTANT! Use rewrite-target only for backend!
      nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    # IMPORTANT! Set real application address before deploy
    - host: learnit.lan
      paths:
        # For frontend: /
        # For backend: /api(/|$)(.*)
        - path: /api(/|$)(.*)
          pathType: Prefix
  tls: []